PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS ExpenseGroups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ExpenseCategories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Payers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PaymentMode (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Expenses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    expense_group_id INTEGER NOT NULL,
    expense_category_id INTEGER NOT NULL,
    payer_id INTEGER NOT NULL,
    payment_mode_id INTEGER NOT NULL,
    date DATE NOT NULL,
    amount REAL NOT NULL,
    expense_description TEXT,
    FOREIGN KEY (expense_group_id) REFERENCES ExpenseGroups(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (expense_category_id) REFERENCES ExpenseCategories(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (payer_id) REFERENCES Payers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (payment_mode_id) REFERENCES PaymentMode(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
